services:
  - type: web
    name: botijas-api
    env: docker
    plan: free
    autoDeploy: true
    dockerContext: .
    dockerfilePath: ./src/Botijas.Api/Dockerfile
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:8080
      - key: CORS__AllowedOrigins
        value: https://botijaslx.vercel.app
      - key: Database__AutoInitialize
        value: "true"
      - key: ConnectionStrings__Default
        sync: false
